// GENERATED FILE - DO NOT EDIT
// Generated by tools/generate_version.dart
// Source: version_config.yaml
// Generated: 2026-01-13T19:06:04.397447Z

/// Application version information
///
/// This file is automatically generated from version_config.yaml
/// Do not edit manually - changes will be overwritten on next build
class VersionInfo {
  VersionInfo._();

  // Project information
  static const String projectName = 'PeerWave';
  static const String projectDescription =
      'Decentralized peer-to-peer communication platform';
  static const String repository = 'https://github.com/simonzander/PeerWave';

  // Client version
  static const String version = '1.1.3';
  static const int buildNumber = 13;
  static const String fullVersion = '$version+$buildNumber';

  // Server compatibility
  static const String minServerVersion = '1.1.0';
  static const String maxServerVersion = '1.2.0';

  // Server version (for reference)
  static const String serverVersion = '1.1.3';
  static const String minClientVersion = '1.1.0';
  static const String maxClientVersion = '1.2.0';

  // Build information
  static const String buildDate = '2026-01-13T19:06:04.397447Z';

  /// Returns a formatted version string for display
  static String get displayVersion => 'v$version';

  /// Returns a detailed version string with build number
  static String get detailedVersion => 'v$version (Build $buildNumber)';

  /// Check if a given server version is compatible with this client
  static bool isServerCompatible(String serverVer) {
    try {
      final server = _parseVersion(serverVer);
      final min = _parseVersion(minServerVersion);
      final max = _parseVersion(maxServerVersion);

      return _compareVersions(server, min) >= 0 &&
          _compareVersions(server, max) <= 0;
    } catch (e) {
      return false;
    }
  }

  /// Parse version string (e.g., "1.2.3" -> [1, 2, 3])
  static List<int> _parseVersion(String version) {
    final cleaned = version.replaceAll(RegExp(r'[^0-9.]'), '');
    return cleaned.split('.').map((e) => int.tryParse(e) ?? 0).toList();
  }

  /// Compare two version arrays (-1: v1 < v2, 0: equal, 1: v1 > v2)
  static int _compareVersions(List<int> v1, List<int> v2) {
    final maxLength = v1.length > v2.length ? v1.length : v2.length;

    for (var i = 0; i < maxLength; i++) {
      final n1 = i < v1.length ? v1[i] : 0;
      final n2 = i < v2.length ? v2[i] : 0;

      if (n1 < n2) return -1;
      if (n1 > n2) return 1;
    }

    return 0;
  }
}
