// GENERATED FILE - DO NOT EDIT
// Generated by tools/generate_version.dart
// Source: version_config.yaml
// Generated: 2026-01-23T11:31:42.108733Z

/**
 * Application version information
 * 
 * This file is automatically generated from version_config.yaml
 * Do not edit manually - changes will be overwritten on next build
 */

// Project information
const projectName = 'PeerWave';
const projectDescription = 'Decentralized peer-to-peer communication platform';
const repository = 'https://github.com/simonzander/PeerWave';

// Server version
const version = '1.1.11';
const minClientVersion = '1.1.0';
const maxClientVersion = '1.2.0';

// Client version (for reference)
const clientVersion = '1.1.11';
const clientBuildNumber = 21;
const minServerVersion = '1.1.0';
const maxServerVersion = '1.2.0';

// Build information
const buildDate = '2026-01-23T11:31:42.108733Z';

/**
 * Returns a formatted version string for display
 */
function getDisplayVersion() {
  return `v\${version}`;
}

/**
 * Check if a given client version is compatible with this server
 * @param {string} clientVer - Client version string (e.g., "1.0.0")
 * @returns {boolean} - True if compatible
 */
function isClientCompatible(clientVer) {
  try {
    const client = parseVersion(clientVer);
    const min = parseVersion(minClientVersion);
    const max = parseVersion(maxClientVersion);
    
    return compareVersions(client, min) >= 0 && 
           compareVersions(client, max) <= 0;
  } catch (e) {
    return false;
  }
}

/**
 * Parse version string (e.g., "1.2.3" -> [1, 2, 3])
 * @param {string} version - Version string
 * @returns {number[]} - Array of version numbers
 */
function parseVersion(version) {
  const cleaned = version.replace(/[^0-9.]/g, '');
  return cleaned.split('.').map(n => parseInt(n) || 0);
}

/**
 * Compare two version arrays
 * @param {number[]} v1 - First version
 * @param {number[]} v2 - Second version
 * @returns {number} - -1 if v1 < v2, 0 if equal, 1 if v1 > v2
 */
function compareVersions(v1, v2) {
  const maxLength = Math.max(v1.length, v2.length);
  
  for (let i = 0; i < maxLength; i++) {
    const n1 = i < v1.length ? v1[i] : 0;
    const n2 = i < v2.length ? v2[i] : 0;
    
    if (n1 < n2) return -1;
    if (n1 > n2) return 1;
  }
  
  return 0;
}

module.exports = {
  // Project info
  projectName,
  projectDescription,
  repository,
  
  // Server version
  version,
  minClientVersion,
  maxClientVersion,
  
  // Client version (reference)
  clientVersion,
  clientBuildNumber,
  minServerVersion,
  maxServerVersion,
  
  // Build info
  buildDate,
  
  // Methods
  getDisplayVersion,
  isClientCompatible,
  parseVersion,
  compareVersions
};
