import 'package:flutter/material.dart';

/// Emoji picker dialog for adding reactions to messages
class EmojiPickerDialog extends StatelessWidget {
  final Function(String emoji) onEmojiSelected;

  const EmojiPickerDialog({super.key, required this.onEmojiSelected});

  // Common emoji categories
  static final List<Map<String, dynamic>> _emojiCategories = [
    {
      'name': 'Smileys',
      'icon': '😊',
      'emojis': [
        '😀',
        '😃',
        '😄',
        '😁',
        '😅',
        '😂',
        '🤣',
        '😊',
        '😇',
        '🙂',
        '🙃',
        '😉',
        '😌',
        '😍',
        '🥰',
        '😘',
        '😗',
        '😙',
        '😚',
        '😋',
        '😛',
        '😝',
        '😜',
        '🤪',
        '🤨',
        '🧐',
        '🤓',
        '😎',
        '🤩',
        '🥳',
        '😏',
        '😒',
        '😞',
        '😔',
        '😟',
        '😕',
        '🙁',
        '☹️',
        '😣',
        '😖',
        '😫',
        '😩',
        '🥺',
        '😢',
        '😭',
        '😤',
        '😠',
        '😡',
        '🤬',
        '🤯',
        '😳',
        '🥵',
        '🥶',
        '😱',
        '😨',
        '😰',
        '😥',
        '😓',
        '🤗',
        '🤔',
        '🤭',
        '🤫',
        '🤥',
        '😶',
        '😐',
        '😑',
        '😬',
        '🙄',
        '😯',
        '😦',
        '😧',
        '😮',
        '😲',
        '🥱',
        '😴',
        '🤤',
        '😪',
        '😵',
        '🤐',
        '🥴',
      ],
    },
    {
      'name': 'Gestures',
      'icon': '👍',
      'emojis': [
        '👍',
        '👎',
        '👊',
        '✊',
        '🤛',
        '🤜',
        '🤞',
        '✌️',
        '🤟',
        '🤘',
        '👌',
        '🤌',
        '🤏',
        '👈',
        '👉',
        '👆',
        '👇',
        '☝️',
        '👋',
        '🤚',
        '🖐',
        '✋',
        '🖖',
        '👏',
        '🙌',
        '👐',
        '🤲',
        '🤝',
        '🙏',
        '✍️',
        '💪',
        '🦾',
      ],
    },
    {
      'name': 'Hearts',
      'icon': '❤️',
      'emojis': [
        '❤️',
        '🧡',
        '💛',
        '💚',
        '💙',
        '💜',
        '🖤',
        '🤍',
        '🤎',
        '💔',
        '❤️‍🔥',
        '❤️‍🩹',
        '💕',
        '💞',
        '💓',
        '💗',
        '💖',
        '💘',
        '💝',
        '💟',
        '☮️',
        '✝️',
        '☪️',
        '🕉',
      ],
    },
    {
      'name': 'Celebration',
      'icon': '🎉',
      'emojis': [
        '🎉',
        '🎊',
        '🎈',
        '🎁',
        '🎀',
        '🎂',
        '🎆',
        '🎇',
        '🧨',
        '✨',
        '🎃',
        '🎄',
        '🎋',
        '🎍',
        '🎎',
        '🎏',
        '🎐',
        '🎑',
        '🧧',
        '🎗',
        '🎟',
        '🎫',
        '🏆',
        '🏅',
        '🥇',
        '🥈',
        '🥉',
        '⚽',
        '⚾',
        '🏀',
        '🏐',
        '🏈',
      ],
    },
    {
      'name': 'Objects',
      'icon': '⭐',
      'emojis': [
        '⭐',
        '🌟',
        '💫',
        '✨',
        '☄️',
        '💥',
        '🔥',
        '🌈',
        '☀️',
        '🌤',
        '⛅',
        '🌥',
        '☁️',
        '🌦',
        '🌧',
        '⛈',
        '🌩',
        '🌨',
        '❄️',
        '☃️',
        '⛄',
        '🌬',
        '💨',
        '💧',
        '💦',
        '☔',
        '☂️',
        '🌊',
        '🌫',
        '🌪',
        '🌀',
        '🌈',
      ],
    },
    {
      'name': 'Animals',
      'icon': '🐶',
      'emojis': [
        '🐶',
        '🐱',
        '🐭',
        '🐹',
        '🐰',
        '🦊',
        '🐻',
        '🐼',
        '🐨',
        '🐯',
        '🦁',
        '🐮',
        '🐷',
        '🐸',
        '🐵',
        '🐔',
        '🐧',
        '🐦',
        '🐤',
        '🦆',
        '🦅',
        '🦉',
        '🦇',
        '🐺',
        '🐗',
        '🐴',
        '🦄',
        '🐝',
        '🪱',
        '🐛',
        '🦋',
        '🐌',
      ],
    },
    {
      'name': 'Food',
      'icon': '🍕',
      'emojis': [
        '🍕',
        '🍔',
        '🍟',
        '🌭',
        '🍿',
        '🧈',
        '🥓',
        '🥚',
        '🍳',
        '🧇',
        '🥞',
        '🧈',
        '🍞',
        '🥐',
        '🥖',
        '🥨',
        '🥯',
        '🥞',
        '🧀',
        '🍖',
        '🍗',
        '🥩',
        '🥪',
        '🌮',
        '🌯',
        '🥙',
        '🧆',
        '🥚',
        '🍲',
        '🍝',
        '🥘',
        '🍜',
      ],
    },
    {
      'name': 'Symbols',
      'icon': '✅',
      'emojis': [
        '✅',
        '❌',
        '❗',
        '❓',
        '❕',
        '❔',
        '‼️',
        '⁉️',
        '💯',
        '🔥',
        '💥',
        '💢',
        '💬',
        '💭',
        '🗯',
        '💤',
        '💨',
        '🕳',
        '🚫',
        '⛔',
        '📵',
        '🚭',
        '🚱',
        '🚷',
        '🚯',
        '🚳',
        '🚹',
        '🚺',
        '🚻',
        '🚼',
        '⚠️',
        '🔞',
      ],
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Dialog(
      backgroundColor: Theme.of(context).colorScheme.surface,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      child: Container(
        width: 400,
        height: 500,
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  'Pick an emoji',
                  style: Theme.of(
                    context,
                  ).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold),
                ),
                IconButton(
                  icon: const Icon(Icons.close),
                  onPressed: () => Navigator.of(context).pop(),
                ),
              ],
            ),
            const SizedBox(height: 16),

            // Emoji grid with categories
            Expanded(
              child: DefaultTabController(
                length: _emojiCategories.length,
                child: Column(
                  children: [
                    // Category tabs
                    TabBar(
                      isScrollable: true,
                      tabs: _emojiCategories.map((category) {
                        return Tab(
                          child: Text(
                            category['icon'] as String,
                            style: const TextStyle(fontSize: 24),
                          ),
                        );
                      }).toList(),
                    ),
                    const SizedBox(height: 8),

                    // Emoji grid
                    Expanded(
                      child: TabBarView(
                        children: _emojiCategories.map((category) {
                          final emojis = category['emojis'] as List<String>;
                          return GridView.builder(
                            gridDelegate:
                                const SliverGridDelegateWithFixedCrossAxisCount(
                                  crossAxisCount: 8,
                                  mainAxisSpacing: 8,
                                  crossAxisSpacing: 8,
                                ),
                            itemCount: emojis.length,
                            itemBuilder: (context, index) {
                              final emoji = emojis[index];
                              return InkWell(
                                onTap: () {
                                  onEmojiSelected(emoji);
                                  Navigator.of(context).pop();
                                },
                                borderRadius: BorderRadius.circular(8),
                                child: Container(
                                  decoration: BoxDecoration(
                                    color: Theme.of(
                                      context,
                                    ).colorScheme.surfaceContainerHighest,
                                    borderRadius: BorderRadius.circular(8),
                                  ),
                                  child: Center(
                                    child: Text(
                                      emoji,
                                      style: const TextStyle(fontSize: 28),
                                    ),
                                  ),
                                ),
                              );
                            },
                          );
                        }).toList(),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  /// Show the emoji picker dialog
  static Future<void> show(
    BuildContext context,
    Function(String emoji) onEmojiSelected,
  ) async {
    await showDialog(
      context: context,
      builder: (context) => EmojiPickerDialog(onEmojiSelected: onEmojiSelected),
    );
  }
}
