#!/usr/bin/env dart
// ignore_for_file: avoid_print

/// Generates version_info.dart from version_config.yaml
/// Run this before every build to ensure version numbers are up-to-date

import 'dart:io';
import 'package:yaml/yaml.dart';

void main() {
  try {
    print('📦 Generating version information...');
    
    // Read version_config.yaml from project root
    final configFile = File('version_config.yaml');
    if (!configFile.existsSync()) {
      print('❌ Error: version_config.yaml not found in project root');
      exit(1);
    }
    
    final yamlString = configFile.readAsStringSync();
    final yaml = loadYaml(yamlString) as YamlMap;
    
    // Extract version information
    final project = yaml['project'] as YamlMap;
    final client = yaml['client'] as YamlMap;
    final server = yaml['server'] as YamlMap;
    
    final projectName = project['name'] as String;
    final projectDescription = project['description'] as String;
    final repository = project['repository'] as String;
    
    final clientVersion = client['version'] as String;
    final buildNumber = client['build_number'] as int;
    final minServerVersion = client['min_server_version'] as String;
    final maxServerVersion = client['max_server_version'] as String;
    
    final serverVersion = server['version'] as String;
    final minClientVersion = server['min_client_version'] as String;
    final maxClientVersion = server['max_client_version'] as String;
    
    final now = DateTime.now().toUtc().toIso8601String();
    
    // Generate Dart code
    final dartCode = '''
// GENERATED FILE - DO NOT EDIT
// Generated by tools/generate_version.dart
// Source: version_config.yaml
// Generated: $now

/// Application version information
/// 
/// This file is automatically generated from version_config.yaml
/// Do not edit manually - changes will be overwritten on next build
class VersionInfo {
  VersionInfo._();
  
  // Project information
  static const String projectName = '$projectName';
  static const String projectDescription = '$projectDescription';
  static const String repository = '$repository';
  
  // Client version
  static const String version = '$clientVersion';
  static const int buildNumber = $buildNumber;
  static const String fullVersion = '\$version+\$buildNumber';
  
  // Server compatibility
  static const String minServerVersion = '$minServerVersion';
  static const String maxServerVersion = '$maxServerVersion';
  
  // Server version (for reference)
  static const String serverVersion = '$serverVersion';
  static const String minClientVersion = '$minClientVersion';
  static const String maxClientVersion = '$maxClientVersion';
  
  // Build information
  static const String buildDate = '$now';
  
  /// Returns a formatted version string for display
  static String get displayVersion => 'v\$version';
  
  /// Returns a detailed version string with build number
  static String get detailedVersion => 'v\$version (Build \$buildNumber)';
  
  /// Check if a given server version is compatible with this client
  static bool isServerCompatible(String serverVer) {
    try {
      final server = _parseVersion(serverVer);
      final min = _parseVersion(minServerVersion);
      final max = _parseVersion(maxServerVersion);
      
      return _compareVersions(server, min) >= 0 && 
             _compareVersions(server, max) <= 0;
    } catch (e) {
      return false;
    }
  }
  
  /// Parse version string (e.g., "1.2.3" -> [1, 2, 3])
  static List<int> _parseVersion(String version) {
    final cleaned = version.replaceAll(RegExp(r'[^0-9.]'), '');
    return cleaned.split('.').map((e) => int.tryParse(e) ?? 0).toList();
  }
  
  /// Compare two version arrays (-1: v1 < v2, 0: equal, 1: v1 > v2)
  static int _compareVersions(List<int> v1, List<int> v2) {
    final maxLength = v1.length > v2.length ? v1.length : v2.length;
    
    for (var i = 0; i < maxLength; i++) {
      final n1 = i < v1.length ? v1[i] : 0;
      final n2 = i < v2.length ? v2[i] : 0;
      
      if (n1 < n2) return -1;
      if (n1 > n2) return 1;
    }
    
    return 0;
  }
}
''';
    
    // Write to client/lib/core/version/version_info.dart
    final outputDir = Directory('client/lib/core/version');
    if (!outputDir.existsSync()) {
      outputDir.createSync(recursive: true);
    }
    
    final outputFile = File('client/lib/core/version/version_info.dart');
    outputFile.writeAsStringSync(dartCode);
    
    print('✅ Generated: ${outputFile.path}');
    print('   Version: $clientVersion (Build $buildNumber)');
    print('   Server compatibility: $minServerVersion - $maxServerVersion');
    
  } catch (e, stackTrace) {
    print('❌ Error generating version info: $e');
    print(stackTrace);
    exit(1);
  }
}
