// File generated by FlutterFire CLI.
// This file is a placeholder and should be regenerated using:
// flutterfire configure
//
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSKUdVE42S7M2pxgThGR0M7MN5mk7_qcU',
    appId: '1:569967816098:web:2f8a0b4c678353235056fb',
    messagingSenderId: '569967816098',
    projectId: 'peerwave-labs',
    authDomain: 'peerwave-labs.firebaseapp.com',
    storageBucket: 'peerwave-labs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADrf4-jJCmR1f-W-oJil3PKl8NyPnWc0M',
    appId: '1:569967816098:android:f4ef99b2865c16f95056fb',
    messagingSenderId: '569967816098',
    projectId: 'peerwave-labs',
    storageBucket: 'peerwave-labs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXvy1dU6S67ML68hLOxO5jCYSsIvcK17M',
    appId: '1:569967816098:ios:867170540d59c4825056fb',
    messagingSenderId: '569967816098',
    projectId: 'peerwave-labs',
    storageBucket: 'peerwave-labs.firebasestorage.app',
    iosBundleId: 'com.example.peerwaveClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXvy1dU6S67ML68hLOxO5jCYSsIvcK17M',
    appId: '1:569967816098:ios:9533d2cdb6eeaa2e5056fb',
    messagingSenderId: '569967816098',
    projectId: 'peerwave-labs',
    storageBucket: 'peerwave-labs.firebasestorage.app',
    iosBundleId: 'org.peerwave.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSKUdVE42S7M2pxgThGR0M7MN5mk7_qcU',
    appId: '1:569967816098:web:6d77f830278e7f085056fb',
    messagingSenderId: '569967816098',
    projectId: 'peerwave-labs',
    authDomain: 'peerwave-labs.firebaseapp.com',
    storageBucket: 'peerwave-labs.firebasestorage.app',
  );
}
